version: '2'
services:
    mysql:
        image: 'mysql:5.7'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: go1
            MYSQL_PASSWORD: go1
        volumes:
            - './.data/mysql:/var/lib/mysql'
        ports:
            - '3306:3306'
    neo4j:
        image: neo4j
        environment:
            - NEO4J_AUTH=none
        ports:
            - '7474:7474'
    queue:
        image: 'rabbitmq:3.6'
        environment:
            - RABBITMQ_DEFAULT_USER=go1
            - RABBITMQ_DEFAULT_PASS=go1
    memcached:
        image: 'memcached:1.4-alpine'
    consumer:
        image: 'registry.code.go1.com.au/microservices/consumer:master'
        command:
            - /app/app
        links:
            - queue
            - web
        environment:
            - 'QUEUE_URL="amqp://go1:go1@queue:5672/"'
            - 'SERVICE_URL_PATTERN=http://web/GO1/SERVICE'
    web:
        image: 'go1com/php:7-nginx'
        links:
            - memcached
            - neo4j
            - mysql
            - queue
        ports:
            - '80:80'
        volumes:
            - './php/:/app/'
            - './php/vendor:/vendor/'
            - './.data/drupal/:/drupal/'
            - './drupal/accounts/:/drupal/sites/accounts/'
            - './.data/nginx/sites-available/:/etc/nginx/sites-available/'
            - './.data/nginx/autoload/:/autoload/'
            - './web/ui/dist/:/var/www/html/'
            - './.data/cli/:/cli/'
            - './scripts/:/scripts/'
        environment:
            - _DOCKER_RDS_DB_NAME=go1
            - _DOCKER_RDS_HOSTNAME=mysql
            - _DOCKER_RDS_PASSWORD=root
            - _DOCKER_RDS_USERNAME=root
            - _DOCKER_CACHE_BACKEND=memcached
            - _DOCKER_CACHE_HOST=memcached
            - _DOCKER_CACHE_PORT=11211
            - _DOCKER_ALGOLIA_URL=http://web/GO1/algolia/
            - _DOCKER_API_URL=http://web/GO1/api/
            - _DOCKER_ASSESSOR_URL=http://web/GO1/assessor/
            - _DOCKER_ASSIGNMENT_URL=http://web/GO1/assignment/
            - _DOCKER_BATCH_URL=http://web/GO1/batch/
            - _DOCKER_CLOUDINARY_URL=http://web/GO1/cloudinary/
            - _DOCKER_CONSOLE_URL=http://web/GO1/console/
            - _DOCKER_CREDIT_URL=http://web/GO1/credit/
            - _DOCKER_CURRENCY_URL=http://web/GO1/currency/
            - _DOCKER_ECK_URL=http://web/GO1/eck/
            - _DOCKER_ENDPOINT_URL=http://web/GO1/endpoint/
            - _DOCKER_ENROLMENT_URL=http://web/GO1/enrolment/
            - _DOCKER_ENTITY_URL=http://web/GO1/entity/
            - _DOCKER_FINDER_URL=http://web/GO1/finder/
            - _DOCKER_GRAPHIN_URL=http://web/GO1/graphin/
            - _DOCKER_HISTORY_URL=http://web/GO1/history/
            - _DOCKER_INDEX_URL=http://web/GO1/index/
            - _DOCKER_LIB_URL=http://web/GO1/lib/
            - _DOCKER_LO_URL=http://web/GO1/lo/
            - _DOCKER_LOB_URL=http://web/GO1/lob/
            - _DOCKER_MAIL_URL=http://web/GO1/mail/
            - _DOCKER_NATERO_URL=http://web/GO1/natero/
            - _DOCKER_NOTE_URL=http://web/GO1/note/
            - _DOCKER_NOTIFY_URL=http://web/GO1/notify/
            - _DOCKER_ONBOARD_URL=http://web/GO1/onboard/
            - _DOCKER_PAYMENT_URL=http://web/GO1/payment/
            - _DOCKER_PORTAL_URL=http://web/GO1/portal/
            - _DOCKER_QUEUE_URL=http://web/GO1/queue/
            - _DOCKER_QUIZ_URL=http://web/GO1/quiz/
            - _DOCKER_RULES_URL=http://web/GO1/rules/
            - _DOCKER_S3_URL=http://web/GO1/s3/
            - _DOCKER_SCRAPING_URL=http://web/GO1/scraping/
            - _DOCKER_SMS_URL=http://web/GO1/sms/
            - _DOCKER_SOCIAL_URL=http://web/GO1/social/
            - _DOCKER_SSO_URL=http://web/GO1/sso/
            - _DOCKER_STAFF_URL=http://web/GO1/staff/
            - _DOCKER_STASH_URL=http://web/GO1/stash/
            - _DOCKER_STATUS_URL=http://web/GO1/status/
            - _DOCKER_SUBSCRIPTION_URL=http://web/GO1/subscription/
            - _DOCKER_UPTIME_URL=http://web/GO1/uptime/
            - _DOCKER_USER_URL=http://web/GO1/user/
            - _DOCKER_VIDEO_URL=http://web/GO1/video/
            - _DOCKER_VOTE_URL=http://web/GO1/vote/
            - _DOCKER_WORKSHOP_URL=http://web/GO1/workshop/
