version: "2"
services:
  mysql:
    image: mysql:5.7
    user: 1000:1000
    environment: { MYSQL_ROOT_PASSWORD: root, MYSQL_USER: root, MYSQL_PASSWORD: root }
    volumes: ["./.data/mysql:/var/lib/mysql"]

  queue:
    image: rabbitmq:3.6

  handler:
    links: [mysql, queue]
    image: go1com/php:php7
    volumes:
      - ./php/:/app/
      - ./php/vendor:/vendor/
      - .data/nginx/autoload/:/autoload/
      - .data/drupal/:/drupal/
      - ./drupal/accounts/:/drupal/sites/accounts/

  web:
    image: go1com/docker-nginx:php
    links: ["handler"]
    ports: ["80:80"]
    volumes:
      - ./php/:/app/
      - ./php/vendor:/vendor/
      - .data/drupal/:/drupal/
      - ./drupal/accounts/:/drupal/sites/accounts/
      - .data/nginx/conf.d/:/etc/nginx/conf.d/
      - ./web/ui/:/var/www/html/
    environment:
      - _DOCKER_RDS_DB_NAME=go1
      - _DOCKER_RDS_HOSTNAME=mysql
      - _DOCKER_RDS_PASSWORD=root
      - _DOCKER_RDS_USERNAME=root
      - _DOCKER_SERVICE_WILDCARD=http://web/GO1/*/
      - _DOCKER_ENROLMENT_URL=http://web/GO1/graphin/
      - _DOCKER_GRAPHIN_URL=http://web/GO1/graphin/
      - _DOCKER_LO_URL=http://web/GO1/lo/
      - _DOCKER_MAIL_URL=http://web/GO1/mail/
      - _DOCKER_OUTCOME_URL=http://web/GO1/outcome/
      - _DOCKER_PORTAL_URL=http://web/GO1/portal/
      - _DOCKER_QUEUE_URL=http://web/GO1/queue/
      - _DOCKER_RULES_URL=http://web/GO1/rules/
      - _DOCKER_USER_URLhttp://web/GO1/user/
