version: '2'
services:
    mysql:
        image: 'mysql:5.7'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: go1
            MYSQL_PASSWORD: go1
        volumes:
            - './.data/mysql:/var/lib/mysql'
        ports:
            - '3306:3306'
    neo4j:
        image: neo4j
        environment:
            - NEO4J_AUTH=none
        ports:
            - '7474:7474'
    queue:
        image: 'rabbitmq:3.6'
        environment:
            - RABBITMQ_DEFAULT_USER=go1
            - RABBITMQ_DEFAULT_PASS=go1
    memcached:
        image: 'memcached:1.4-alpine'
    consumer:
        image: 'registry.code.go1.com.au/microservices/consumer:master'
        command:
            - /app/app
        links:
            - queue
            - web
        environment:
            - 'QUEUE_URL="amqp://go1:go1@queue:5672/"'
            - 'SERVICE_URL_PATTERN=http://web/GO1/SERVICE'
    ui:
        image: 'registry.code.go1.com.au/apiom/apiom-ui:master'
        command: ["ping", "127.0.0.1", "-q"]
    web:
        image: 'go1com/php:7-nginx'
        links:
            - memcached
            - neo4j
            - mysql
            - queue
        ports:
            - '80:80'
        volumes:
            - './php/:/app/'
            - './php/vendor:/vendor/'
            - './.data/drupal/:/drupal/'
            - './.data/nginx/sites-available/:/etc/nginx/sites-available/'
            - './.data/nginx/autoload/:/autoload/'
            - './.data/cli/:/cli/'
            - './scripts/:/scripts/'
            - './.data/resources/docker/:/app/resources/docker/'
        volumes_from:
              - ui
        environment:
            - _DOCKER_RDS_DB_NAME=go1
            - _DOCKER_RDS_HOSTNAME=mysql
            - _DOCKER_RDS_PASSWORD=root
            - _DOCKER_RDS_USERNAME=root
            - _DOCKER_CACHE_BACKEND=memcached
            - _DOCKER_CACHE_HOST=memcached
            - _DOCKER_CACHE_PORT=11211
            - SERVICE_URL_PATTERN=http://web/GO1/SERVICE
