version: "2"
services:
  data:
    image: registry.code.go1.com.au/microservices/enrolment:${CI_BUILD_REF_NAME}
    cpu_shares: 8
    mem_limit: 8000000
    command: ["ping", "127.0.0.1", "-q"]
  web:
    image: go1com/php:7-nginx
    cpu_shares: 32
    mem_limit: 67108864
    ports: ["80"]
    volumes_from: ["data"]
    environment:
      - SERVICE_TAGS
      - SERVICE_80_NAME
      - _DOCKER_ACCOUNTS_NAME
      - _DOCKER_CACHE_BACKEND
      - _DOCKER_CACHE_HOST
      - _DOCKER_CACHE_PORT
      - _DOCKER_ENV
      - _DOCKER_QUEUE_HOST
      - _DOCKER_QUEUE_PASSWORD
      - _DOCKER_QUEUE_PORT
      - _DOCKER_QUEUE_USER
      - _DOCKER_XXXXX_DB_HOST
      - _DOCKER_XXXXX_DB_NAME
      - _DOCKER_XXXXX_DB_PASSWORD
      - _DOCKER_XXXXX_DB_PORT
      - _DOCKER_XXXXX_DB_SLAVE
      - _DOCKER_XXXXX_DB_USERNAME
